export * from './prisma.service'
export * from './college.service'
export * from './category.service'
export * from './street.service'
export * from './course.service'
export * from './course-area.service'
export * from './graduation-type.service'
export * from './teaching-modality.service'